apiVersion: v1
kind: Service
metadata:
  name: bookinfo-dev-details
  namespace: student27-bookinfo-dev
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8081
  selector:
    app: bookinfo-dev-details