details:
  namespace: student27-bookinfo-dev
  image: ghcr.io/bordee2000/bookinfo-details
  tag: dev
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8081
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: itkmitl.bookinfo.dev.opsta.net
  path: "/student27/details(/|$)(.*)"
  serviceType: ClusterIP